# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb65d97bced2d01e6fc3125b8169eb04142dc1a0a2af394fc60d38ce74c2127ac60ea9c9855f4fe43a35555a630315d4c7b2a020e962d34b0ec7d5eefea137a

test:
  secret_key_base: c928a2c4aa4e7b5cdba077d8ffb7839f6abbaf9c971b0c065654768691f4a8f2ef6caca7a67b1312c59a34aa5d56c2f9476a2fa463bf304639c1112c2ec7c9f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
